name: Go CI

on:
  push:
    branches: [main, release/next]
  pull_request:
    branches: [main, release/next]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.24.2'  # or the version you're using

      # Cache the Go modules
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Install dependencies
      - name: Install dependencies
        run: go mod download

      # Run the tests
      - name: Run tests
        env:
          APP_ENV: test  # Set your environment variable if needed
        run: go test -v ./...
